language: C++
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libwxgtk3.0-dev

before_script:
 - mkdir build
 - cd build
 - cmake -D LITESQL_WITH_DOCS:bool=ON -D LITESQL_WITH_MYSQL:bool=ON -D LITESQL_WITH_SQLITE3:bool=ON -D LITESQL_WITH_TESTS:bool=ON -D LITESQL_WITH_UI:bool=OFF ..
        
script:
 - cmake --build . --target all 
 - cmake --build . --target test 
 - cmake --build . --target package 
 - cmake --build . --target dist
 - cmake --build . --target package_source
