version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\litesql
image:
# - Visual Studio 2013
# - Visual Studio 2015
- Visual Studio 2017
- Visual Studio 2019
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: false

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
#- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
#- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake ..  -D LITESQL_USE_SYSTEM_EXPAT:bool=OFF -D LITESQL_USE_SYSTEM_SQLITE:bool=OFF -D LITESQL_WITH_DOCS:bool=ON -D LITESQL_WITH_MYSQL:bool=OFF -D LITESQL_WITH_SQLITE:bool=ON -D LITESQL_WITH_TESTS:bool=ON -D LITESQL_WITH_UI:bool=OFF -D LITESQL_MSVC_MT:BOOL=ON -G %generator%

build_script:
 - cmake --build . --target ALL_BUILD 
 - cmake --build . --target package 
 - cpack --config CPackSourceConfig.cmake

test_script:
# - cd build
  - set CTEST_OUTPUT_ON_FAILURE=1
  - ctest -C %configuration% 
  - cd ..

#build:
#  project: c:\projects\litesql\build\litesql.sln
#  verbosity: minimal
#  parallel: true
  
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - cmake/